### PR TITLE
Fixed empty readBuf issue

### PR DESCRIPTION
**Pull request by donpui**
Due to double pointers (my guess) misbehaviour happen in nhooyr/websocket ws_js.go library.
On receiver side, when wsMessage appear, it was appended to c.readBuf
https://github.com/nhooyr/websocket/blob/8dee580a7f74cf1713400307b4eee514b927870f/ws_js.go#L81
and signal created: case c.readSignal <- struct{}{}:

Then in read function, when signal appear, we tried to read from the same c.readBuf, however it was empty and we got go panic:
panic: runtime error: index out of range [0] with length 0 (https://github.com/nhooyr/websocket/issues/349)
https://github.com/nhooyr/websocket/blob/8dee580a7f74cf1713400307b4eee514b927870f/ws_js.go#L132

c.readBuf in init() and read() functions had different memory addresses.

Changing *wsconn -> wsconn, which itself is pointer, allowed to solve an issue, without any changes on nhooyr/websocket library.

---

## Code Review Checklist (to be filled out by reviewer)

- [ ] Description accurately reflects what changes are being made.
- [ ] Description explains why the changes are being made (or references an issue containing one).
- [ ] The PR appropriately sized.
- [ ] New code has enough tests. 
- [ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".
- [ ] Existing documentation is up-to-date, if impacted.

### CODE REVIEW

**Comment by meejah** [comment]
Is there something describing the issue?

**Comment by donpui** [comment]
> 

Add in description, as it was quick PR for others to try

**Comment by piegamesde** [comment]
I'm uneasy with calling it a day on this issue yet. It sounds like a ticking time bomb, something waiting to come back and steal us yet another few weeks after the next refactoring. We really should try and get a deeper understanding of the underlying issue.

**Comment by donpui** [comment]
Leaving two references which explains the problem here:
https://go.dev/doc/faq#methods_on_values_or_pointers
https://eli.thegreenplace.net/2018/beware-of-copying-mutexes-in-go/

**Pull request merged**
